### ISSUE TITLE
Error while reading dialectid data

### ISSUE THREAD

**Issue by abmhidy** [CAMeL-Lab/camel_tools#17] opened 2020-09-03 11:01 UTC
The home directory  /Users/owo/ is not correct

Traceback (most recent call last):
  File "kenlm.pyx", line 114, in kenlm.Model.__init__ (python/kenlm.cpp:2132)
RuntimeError: util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'.
No such file or directory while opening /Users/owo/.camel_tools/data/dialectid/default/lm/char/BAS.arpa

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "testdilectID.py", line 3, in <module>
    did = DialectIdentifier.pretrained()
  File "/home/amahdaouy/.conda/envs/arbnlp/lib/python3.6/site-packages/camel_tools/dialectid/__init__.py", line 447, in pretrained
    return dill.load(model_fp)
  File "/home/amahdaouy/.local/lib/python3.6/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/amahdaouy/.local/lib/python3.6/site-packages/dill/_dill.py", line 473, in load
    obj = StockUnpickler.load(self)
  File "kenlm.pyx", line 117, in kenlm.Model.__init__ (python/kenlm.cpp:2242)
OSError: Cannot read model 'b'/Users/owo/.camel_tools/data/dialectid/default/lm/char/BAS.arpa'' (util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /Users/owo/.camel_tools/data/dialectid/default/lm/char/BAS.arpa)

**Comment by owo** [comment] 2020-09-03 12:43
Hi @abmhidy ,

Thanks for bringing this up.

This is caused by the pre-trained models using absolute paths when being saved to disk using `dill`.

I'll update you when this is fixed.

**Comment by abmhidy** [comment] 2020-09-03 12:46
Hi @owo  Thank you

**Comment by owo** [comment] 2020-09-13 11:09
Hi @abmhidy,

The issue should be fixed now.
Can you please re-download and re-install the zipped data as well as re-install camel-tools from the latest `master` copy and let me know if it works?
You may need to do `pip install --upgrade --force-reinstall .` to insure the source files are actually re-installed.

**Comment by abmhidy** [comment] 2020-09-13 18:35
Hi @owo,

The issue is fixed, many thanks

**Closed** 2020-09-13 18:39 UTC

**Comment by ahmedbr** [comment] 2022-04-12 11:02
Hi @owo 

At the beginning, I had the same error. It's solved after running the command you wrote [here](https://github.com/CAMeL-Lab/camel_tools/issues/17#issuecomment-691657364)
#17#issuecomment-691657364

But now I have another error as following:


`
Traceback (most recent call last):
  File "kenlm.pyx", line 139, in kenlm.Model.__init__
RuntimeError: util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'.
No such file or directory while opening /home/user1/.camel_tools/data/dialectid/default/lm/char/TRI.arpa

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dialect_id.py", line 5, in <module>
    obj = DialectIdentifier()
  File "/home/mustafa.erden/miniconda3/envs/torch/lib/python3.8/site-packages/camel_tools/dialectid/__init__.py", line 343, in __init__
    self._load_lms(char_lm_dir, word_lm_dir)
  File "/home/mustafa.erden/miniconda3/envs/torch/lib/python3.8/site-packages/camel_tools/dialectid/__init__.py", line 355, in _load_lms
    self._char_lms[label] = kenlm.Model(str(char_lm_path), config)
  File "kenlm.pyx", line 142, in kenlm.Model.__init__
OSError: Cannot read model '/home/user1/.camel_tools/data/dialectid/default/lm/char/TRI.arpa' (util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /home/user1/.camel_tools/data/dialectid/default/lm/char/TRI.arpa)

`

**Comment by owo** [comment] 2022-04-14 10:03
Hi @ahmedbr

Did you run the [data download step](https://github.com/CAMeL-Lab/camel_tools#installing-data)?

**Comment by ahmedbr** [comment] 2022-04-14 11:12
> Hi @ahmedbr
> 
> Did you run the [data download step](https://github.com/CAMeL-Lab/camel_tools#installing-data)?

Hi @owo 
Unfortunately, because I got an error message when tried to install the full version of the dataset, only the `light` version was installed.

the error message was as this:

Error: An error occured while extracting downloaded data.

**Comment by owo** [comment] 2022-04-22 08:30
Hi @ahmedbr 

This is an issue with how we used to distribute the data (through Google Drive).

You need to first update to the latest camel-tools by running `pip install --upgrade --force-reinstall camel-tools` and then reinstalling the data by running `camel_data -i all`.

Hope that helps.
